---

#- name: Alpine | enable community repository
#  lineinfile: dest=/etc/apk/repositories line='http://dl-2.alpinelinux.org/alpine/v3.3/community'

- name: Alpine | Extra packages install
  apk: name={{item}} state=present update_cache=yes
  with_items:
    - openssh
    - acl
    - ca-certificates
    - logcheck

- block:
    - name: Alpine | openntpd install
      apk: name=openntpd state=present
    - name: Review ntpd configuration
      replace:
        dest='/etc/ntpd.conf' regexp="{{ item.regexp }}" replace='{{ item.replace }}'
      with_items:
        - { regexp: '^#listen on 127.0.0.1', replace: 'listen on 127.0.0.1' }
      notify:
        - restart openntpd
    - name: ensure openntpd service enabled
      service: name=openntpd state=started enabled=yes
  when: >
    monitor_ntp and
    (ansible_virtualization_type is not defined or
      (ansible_virtualization_type != "lxc" and ansible_virtualization_type != "docker")
    )

- name: add rsyslog logrotate.d configuration with permissions for nagios
  template: src=rsyslog dest=/etc/logrotate.d/rsyslog mode=0644 backup=yes

- acl: name=/var/log/messages entity=nagios etype=user permissions="r" state=present

- name: ensure services are enabled
  service: name="{{ item }}" state=started enabled=yes
  with_items:
    - sshd
    - nrpe
