---

- include: debian.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

#- include: redhat.yml
#  when: ansible_os_family == "RedHat"

- include: alpine.yml
  when: ansible_os_family == "Alpine"

#- include: darwin.yml
#  when: ansible_os_family == 'Darwin'

- block:
    - name: ensure logcheck dir exists
      file: dest=/etc/logcheck/ignore.d.workstation mode=0755 state=directory
    - name: whitelist connection attemps from server - logcheck
      template: src=logcheck-ignore-monserver dest=/etc/logcheck/ignore.d.workstation/monserver mode=0644
  when: ansible_system == 'Linux'
