---

- name: Debian | Extra packages install
  apt: name={{ monclient_pkgs }} state=present update_cache=yes cache_valid_time=3600 install_recommends=no

- block:
    - name: Debian | openntpd install
      apt: name=openntpd state=present
    - name: Review ntpd configuration
      replace:
        dest='/etc/openntpd/ntpd.conf' regexp="{{ item.regexp }}" replace='{{ item.replace }}'
      with_items:
        - { regexp: '^#listen on 127.0.0.1', replace: 'listen on 127.0.0.1' }
      notify:
        - restart openntpd
  when: >
    monitor_ntp and
    (ansible_virtualization_type is not defined or
      (ansible_virtualization_type != "lxc" and ansible_virtualization_type != "docker")
    )

#- user: name=nagios groups=ossec append=yes

- name: add rsyslog logrotate.d configuration with permissions for nagios
  template: src=rsyslog dest=/etc/logrotate.d/rsyslog mode=0644 backup=yes

- stat: path=/var/log/syslog
  register: log_syslog
- acl: name=/var/log/syslog entity=nagios etype=user permissions="r" state=present
  when: log_syslog.stat.exists
