---
- include: debian.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- include: redhat.yml
  when: ansible_os_family == "RedHat" or ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- include: darwin.yml
  when: ansible_os_family == 'Darwin'

- name: adding extra check_* scripts
  copy: "src={{ item }} dest={{ np }} owner=root mode=0755"
  with_items:
    - check_aide.pl
    - check_ossec.pl
    - count_file.pl
    - check_snortalerts.pl
    - check_updates.pl
## http://exchange.nagios.org/directory/Plugins/Operating-Systems/Linux/check_updatetime/details
    - check_updatetime

- name: download Linux check_mem
  get_url: url=https://raw.githubusercontent.com/jasonhancock/nagios-memory/master/plugins/check_mem dest={{ np }}/check_mem mode=0755
  when: ansible_system == 'Linux'

#
### template as ansible template conf file?
### (old nagios/nrpe client way)
#

#- shell: "ifconfig {{ if_icinga }} | awk -F'[ :]' '/inet addr/ {print $13}'"
#  changed_when: False
#  register: ipaddr
- name: set monitor target - loopback
  set_fact:
    targethost: 127.0.0.1
  when: monclient_useloopback is defined and monclient_useloopback
## Note: try to change target to localhost automatically when applicable but NOK
#  when: monclient_server == ansible_all_ipv4_addresses | ipaddr('public') | string
- name: set monitor target - ansible_fqdn
  set_fact:
    targethost: "{{ ansible_fqdn }}"
  when: monclient_useloopback is not defined or not monclient_useloopback
#  when: monclient_server != ansible_all_ipv4_addresses | ipaddr('public') | string
#- debug: var=targethost
#- debug: var=monclient_server
#- debug: var=ansible_all_ipv4_addresses | ipaddr('public') | string

- name: monclient_server
  debug: var=monclient_server
- stat: path=/etc/icinga2/conf.d/commands-custom.conf
  register: nrpecmd
  delegate_to: "{{ monclient_server }}"
  changed_when: False
  when: monclient_server is defined and monclient_server != 'test-kitchen'
- fail: msg="Server is not configured. Missing commands-custom.conf... Stopping!"
  when: not nrpecmd.stat.exists and monclient_server is defined and monclient_server != 'test-kitchen'

- name: ensure right permissions for /etc/icinga2/conf.d
  file: dest=/etc/icinga2/conf.d state=directory mode=0755
- debug: var=targethost
- debug: var=monclient_server
- name: deploy client configuration on icinga2 server
  template: src=hosts-template.conf dest="/etc/icinga2/conf.d/hosts-monclient-{{ targethost }}.conf" mode=0644
  delegate_to: "{{ monclient_server }}"
  notify:
    - restart icinga2 server
#  when: nrpe_mode is defined and nrpe_mode
## FIXME! monclient_server conditions does not seem to work
  when: monclient_type is defined and monclient_type == 'icinga2' and monclient_server is defined and monclient_server != "" and monclient_server != 'test-kitchen'

- name: deploy client configuration on nagios server
  template: src=hosts-template-nagios.cfg dest=/etc/nagios3/conf.d/hosts-monclient-{{ ansible_fqdn }}.cfg mode=0644
  delegate_to: "{{ monclient_server }}"
  notify:
    - restart nagios server
  when: monclient_type is defined and monclient_type == 'nagios' and monclient_server is defined and monclient_server != "" and monclient_server != 'test-kitchen'

- name: add client to server /etc/hosts
  lineinfile: dest=/etc/hosts line="{{ ansible_eth0.ipv4.address }} {{ ansible_hostname }} {{ ansible_hostname }}.home"
  delegate_to: "{{ monclient_server }}"
  when: monclient_add_to_etchosts is defined and monclient_add_to_etchosts and monclient_server != "" and monclient_server != 'test-kitchen'

