---

- name: Set fact nagios plugins path for redhat
  set_fact:
    np: /usr/lib64/nagios/plugins

- name: yum | Extra packages install
  yum: name={{ monclient_pkgs }} state=present

- name: Redhat | Ensure services are enabled and started
  service: name={{ item }} state=started enabled=yes
  with_items:
    - nrpe
    - snmpd
