---

- set_fact:
    np: /usr/lib64/nagios/plugins

- name: yum | Extra packages install
  yum: name={{item}} state=present
  with_items: "{{ monclient_pkgs }}"

- name: Redhat | Ensure services are enabled and started
  service: name={{ item }} state=started enabled=yes
  with_items:
    - nrpe
    - snmpd

