---

- debug: var=targethost
- debug: var=monclient_server
- name: remove client configuration on icinga2 server
  file: dest="/etc/icinga2/conf.d/hosts-monclient-{{ inventory_hostname }}.conf" state=absent
  delegate_to: "{{ monclient_server }}"
  notify:
    - restart icinga2 server
  when: >
    monclient_type is defined and monclient_type == 'icinga2' and
    monclient_server is defined and monclient_server and monclient_server != 'test-kitchen'

- name: remove client configuration on nagios server
  file: dest=/etc/nagios3/conf.d/hosts-monclient-{{ inventory_hostname }}.cfg state=absent
  delegate_to: "{{ monclient_server }}"
  notify:
    - restart nagios server
  when: >
    monclient_type is defined and monclient_type == 'nagios' and
    monclient_server is defined and monclient_server and monclient_server != 'test-kitchen'
