---
- name: restart nrpe
  service: name=nagios-nrpe-server state=restarted
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu' or ansible_os_family == "Alpine"

- name: restart nrpe - darwin
  command: "{{ item }}"
  with_items:
    - launchctl unload -w /Library/LaunchDaemons/org.macports.nrpe.plist
    - launchctl load -w /Library/LaunchDaemons/org.macports.nrpe.plist
  when: ansible_os_family == 'Darwin'

- name: restart openntpd
  service: name=openntpd state=restarted

- name: restart icinga2 server
  service: name=icinga2 state=restarted
  delegate_to: "{{ monclient_server }}"
  when: monclient_server is defined and monclient_server != ""

- name: restart nagios server
  service: name=nagios3 state=restarted
  delegate_to: "{{ monclient_server }}"
  when: monclient_server is defined and monclient_server != ""

